//! Persistent app config stored at `~/.config/sourceflow/state.json`.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};

/// Single persisted tab entry. `id` is a UUID generated by the frontend so
/// it survives a process restart and can be re-attached to the same Zustand
/// store slot on reload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersistedTab {
    pub id: String,
    pub path: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct PersistedState {
    /// All open tabs, in user-defined order. The frontend reuses the IDs
    /// when re-opening so React state slots stay stable.
    pub tabs: Vec<PersistedTab>,

    /// ID of the currently-focused tab, if any.
    pub active_tab_id: Option<String>,

    /// Recently-closed tabs (paths only) for the `[+]` button dropdown.
    /// Capped to 10 on save.
    pub recently_closed: Vec<String>,

    /// Phase 1 legacy field. Kept for migration: on first load after
    /// upgrading, if `tabs` is empty but `last_repo_path` is set, the
    /// frontend will convert it into a single tab and clear this field.
    pub last_repo_path: Option<String>,

    /// GitHub OAuth App client_id, set by the user through the UI. Stored
    /// in plaintext on purpose - OAuth client IDs are public by design
    /// (only the missing client_secret keeps the device flow safe). This
    /// supersedes the SOURCEFLOW_GH_CLIENT_ID env var when set.
    pub github_client_id: Option<String>,

    /// When set, passed to `git -c merge.tool=<name> mergetool` instead of the
    /// user's global git config.
    pub merge_tool: Option<String>,
}

fn config_dir() -> AppResult<PathBuf> {
    let base = dirs::config_dir()
        .ok_or_else(|| AppError::Config("could not determine config dir".into()))?;
    Ok(base.join("sourceflow"))
}

fn state_path() -> AppResult<PathBuf> {
    Ok(config_dir()?.join("state.json"))
}

pub fn load() -> AppResult<PersistedState> {
    let path = state_path()?;
    if !path.exists() {
        return Ok(PersistedState::default());
    }
    let data = fs::read_to_string(&path)?;
    let parsed = serde_json::from_str(&data)?;
    Ok(parsed)
}

pub fn save(state: &PersistedState) -> AppResult<()> {
    let dir = config_dir()?;
    fs::create_dir_all(&dir)?;
    let path = state_path()?;
    let mut to_write = state.clone();
    if to_write.recently_closed.len() > 10 {
        to_write.recently_closed.truncate(10);
    }
    let json = serde_json::to_string_pretty(&to_write)?;
    fs::write(&path, json)?;
    Ok(())
}

/// Read just the persisted GitHub client_id without disturbing other fields.
pub fn load_github_client_id() -> AppResult<Option<String>> {
    Ok(load()?.github_client_id)
}

/// Write the GitHub client_id (or clear it with `None`), preserving all
/// other persisted state.
pub fn save_github_client_id(id: Option<String>) -> AppResult<()> {
    let mut state = load()?;
    state.github_client_id = id.map(|s| s.trim().to_string()).filter(|s| !s.is_empty());
    save(&state)
}

pub fn load_merge_tool_settings() -> AppResult<crate::git::types::MergeToolSettings> {
    let state = load()?;
    Ok(crate::git::types::MergeToolSettings {
        merge_tool: state.merge_tool,
    })
}

pub fn save_merge_tool_settings(settings: &crate::git::types::MergeToolSettings) -> AppResult<()> {
    let mut state = load()?;
    state.merge_tool = settings
        .merge_tool
        .as_ref()
        .map(|s| s.trim().to_string())
        .filter(|s| !s.is_empty());
    save(&state)
}
