//! Persistent app config stored at `~/.config/sourceflow/state.json`.

use std::fs;
use std::path::PathBuf;

use serde::{Deserialize, Serialize};

use crate::error::{AppError, AppResult};

/// Single persisted tab entry. `id` is a UUID generated by the frontend so
/// it survives a process restart and can be re-attached to the same Zustand
/// store slot on reload.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PersistedTab {
    pub id: String,
    pub path: String,
}

#[derive(Debug, Clone, Default, Serialize, Deserialize)]
#[serde(default)]
pub struct PersistedState {
    /// All open tabs, in user-defined order. The frontend reuses the IDs
    /// when re-opening so React state slots stay stable.
    pub tabs: Vec<PersistedTab>,

    /// ID of the currently-focused tab, if any.
    pub active_tab_id: Option<String>,

    /// Recently-closed tabs (paths only) for the `[+]` button dropdown.
    /// Capped to 10 on save.
    pub recently_closed: Vec<String>,

    /// Phase 1 legacy field. Kept for migration: on first load after
    /// upgrading, if `tabs` is empty but `last_repo_path` is set, the
    /// frontend will convert it into a single tab and clear this field.
    pub last_repo_path: Option<String>,
}

fn config_dir() -> AppResult<PathBuf> {
    let base = dirs::config_dir()
        .ok_or_else(|| AppError::Config("could not determine config dir".into()))?;
    Ok(base.join("sourceflow"))
}

fn state_path() -> AppResult<PathBuf> {
    Ok(config_dir()?.join("state.json"))
}

pub fn load() -> AppResult<PersistedState> {
    let path = state_path()?;
    if !path.exists() {
        return Ok(PersistedState::default());
    }
    let data = fs::read_to_string(&path)?;
    let parsed = serde_json::from_str(&data)?;
    Ok(parsed)
}

pub fn save(state: &PersistedState) -> AppResult<()> {
    let dir = config_dir()?;
    fs::create_dir_all(&dir)?;
    let path = state_path()?;
    let mut to_write = state.clone();
    if to_write.recently_closed.len() > 10 {
        to_write.recently_closed.truncate(10);
    }
    let json = serde_json::to_string_pretty(&to_write)?;
    fs::write(&path, json)?;
    Ok(())
}
