use std::collections::HashMap;
use std::path::PathBuf;
use std::sync::Mutex;

use crate::error::{AppError, AppResult};

/// Identifier for an open repository tab.
///
/// Generated by the frontend (e.g. `crypto.randomUUID()`) so the React side
/// owns the lifetime of tab identifiers. The backend simply registers them
/// in a `HashMap`. This keeps tab semantics (order, focus, recently-closed)
/// entirely in the UI layer.
pub type TabId = String;

/// Shared application state owned by Tauri.
///
/// Phase 2 changes:
///   * `repo_path: Option<PathBuf>` → `tabs: HashMap<TabId, PathBuf>`
///   * Every command takes a `tab_id` parameter and resolves through this map.
///
/// `Repository` (from `git2`) is `!Send + !Sync`, so we still don't cache it -
/// commands re-open by path on each invocation. libgit2's open is cheap
/// (filesystem stat of `.git/HEAD` essentially); the cost is dominated by the
/// actual operation. If profiling shows hotspots later we can introduce a
/// per-tab worker thread that owns its own `Repository`.
pub struct AppState {
    inner: Mutex<Inner>,
}

struct Inner {
    tabs: HashMap<TabId, PathBuf>,
}

impl AppState {
    pub fn new() -> Self {
        Self {
            inner: Mutex::new(Inner {
                tabs: HashMap::new(),
            }),
        }
    }

    pub fn register_tab(&self, tab_id: TabId, path: PathBuf) {
        let mut inner = self.inner.lock().expect("AppState mutex poisoned");
        inner.tabs.insert(tab_id, path);
    }

    pub fn remove_tab(&self, tab_id: &str) {
        let mut inner = self.inner.lock().expect("AppState mutex poisoned");
        inner.tabs.remove(tab_id);
    }

    pub fn tab_path(&self, tab_id: &str) -> Option<PathBuf> {
        let inner = self.inner.lock().expect("AppState mutex poisoned");
        inner.tabs.get(tab_id).cloned()
    }

    pub fn require_tab_path(&self, tab_id: &str) -> AppResult<PathBuf> {
        self.tab_path(tab_id)
            .ok_or_else(|| AppError::InvalidArg(format!("unknown tab id: {tab_id}")))
    }
}
